IF NOT EXISTS (SELECT 1 FROM sys.server_principals WHERE name = N'IIS APPPOOL\DD35UtilApi')
    CREATE LOGIN [IIS APPPOOL\DD35UtilApi] FROM WINDOWS;

IF NOT EXISTS (SELECT 1 FROM sys.database_principals WHERE name = N'IIS APPPOOL\DD35UtilApi')
    CREATE USER [IIS APPPOOL\DD35UtilApi] FOR LOGIN [IIS APPPOOL\DD35UtilApi];

IF IS_ROLEMEMBER(N'db_datareader', N'IIS APPPOOL\DD35UtilApi') = 0
    ALTER ROLE db_datareader ADD MEMBER [IIS APPPOOL\DD35UtilApi];